### ISSUE TITLE
wrong font, not a tar archive

### ISSUE THREAD

**Issue by stueja** [fam007e/nerd_fonts_installer#1]
I picked #10 (CaskaydiaCove) and #11 (CascaydiaMono) from the font selection, but the script wanted to install #9 (BlexMono) and #10 instead.

Installation itself didn't work because the downloaded file didn't look like an archive to tar.

```
Select fonts to install (separate with spaces):
---------------------------------------------
                                             1  0xProto Nerd Font                     2 3270 Nerd Font
     3  Agave Nerd Font                       4 AnonymicePro Nerd Font                5 Arimo Nerd Font
     6  AurulentSansMono Nerd Font            7 BigBlueTerminal Nerd Font             8 BitstromWera Nerd Font
     9  BlexMono Nerd Font                   10 CaskaydiaCove Nerd Font              11 CaskaydiaMono Nerd Font
    12  CodeNewRoman Nerd Font               13 ComicShannsMono Nerd Font            14 CommitMono Nerd Font
    15  Cousine Nerd Font                    16 D2Coding Nerd Font                   17 DaddyTimeMono Nerd Font
    18  DejaVuSansMono Nerd Font             19 DroidSansMono Nerd Font              20 EnvyCodeR Nerd Font
    21  FantasqueSansMono Nerd Font          22 FiraCode Nerd Font                   23 FiraMono Nerd Font
    24  GeistMono Nerd Font                  25 GoMono Nerd Font                     26 Gohu Nerd Font
    27  Hack Nerd Font                       28 Hasklug Nerd Font                    29 HeavyDataMono Nerd Font
    30  Hurmit Nerd Font                     31 iM-Writing Nerd Font                 32 Inconsolata Nerd Font
    33  InconsolataGo Nerd Font              34 InconsolataLGC Nerd Font             35 IntoneMono Nerd Font
    36  Iosevka Nerd Font                    37 IosevkaTerm Nerd Font                38 IosevkaTermSlab Nerd Font
    39  JetBrainsMono Nerd Font              40 Lekton Nerd Font                     41 Literation Nerd Font
    42  Lilex Nerd Font                      43 MartianMono Nerd Font                44 Meslo Nerd Font
    45  Monaspice Nerd Font                  46 Monofur Nerd Font                    47 Monoid Nerd Font
    48  Mononoki Nerd Font                   49 M+ Nerd Font                         50 Noto Nerd Font
    51  OpenDyslexic Nerd Font               52 Overpass Nerd Font                   53 ProFont Nerd Font
    54  ProggyClean Nerd Font                55 RecMono Nerd Font                    56 RobotoMono Nerd Font
    57  SauceCodePro Nerd Font               58 ShureTechMono Nerd Font              59 SpaceMono Nerd Font
    60  Terminess Nerd Font                  61 Tinos Nerd Font                      62 Ubuntu Nerd Font
    63  UbuntuMono Nerd Font                 64 VictorMono Nerd Font                 65 ZedMono Nerd Font

---------------------------------------------
Enter the numbers of the fonts to install (e.g., "1 2 3"):
10 11
Downloading and installing BlexMono Nerd Font
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Downloading and installing CaskaydiaCove Nerd Font
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Font directories:
        /home/jan/.local/share/fonts
        /usr/local/share/fonts
        /usr/share/fonts
        /home/jan/.fonts
/home/jan/.local/share/fonts: skipping, existing cache is valid: 0 fonts, 0 dirs
/usr/local/share/fonts: skipping, no such directory
/usr/share/fonts: skipping, no such directory
/home/jan/.fonts: skipping, no such directory
/var/cache/fontconfig: not cleaning non-existent cache directory
/home/jan/.cache/fontconfig: cleaning cache directory
/home/jan/.fontconfig: not cleaning non-existent cache directory
```

I removed the instruction `rm` instruction in line 164 to have a look at the files. Also I chose #11 and #12 now. Both fonts are 9 bytes long.

```
❯ ll tmp
total 16K
drwxr-xr-x 2 jan 4.0K Sep 25 11:03 .
drwx------ 9 jan 4.0K Sep 25 11:03 ..
-rw-r--r-- 1 jan    9 Sep 25 11:03 CaskaydiaCove.tar.xz
-rw-r--r-- 1 jan    9 Sep 25 11:03 CaskaydiaMono.tar.xz
❯ cat tmp/CaskaydiaCove.tar.xz
Not Found%      
```

**Comment by fam007e** [comment]
> I picked #10 (CaskaydiaCove) and #11 (CascaydiaMono) from the font selection, but the script wanted to install #9 (BlexMono) and #10 instead.
> 
> Installation itself didn't work because the downloaded file didn't look like an archive to tar.
> 
> ```
> Select fonts to install (separate with spaces):
> ---------------------------------------------
>                                              1  0xProto Nerd Font                     2 3270 Nerd Font
>      3  Agave Nerd Font                       4 AnonymicePro Nerd Font                5 Arimo Nerd Font
>      6  AurulentSansMono Nerd Font            7 BigBlueTerminal Nerd Font             8 BitstromWera Nerd Font
>      9  BlexMono Nerd Font                   10 CaskaydiaCove Nerd Font              11 CaskaydiaMono Nerd Font
>     12  CodeNewRoman Nerd Font               13 ComicShannsMono Nerd Font            14 CommitMono Nerd Font
>     15  Cousine Nerd Font                    16 D2Coding Nerd Font                   17 DaddyTimeMono Nerd Font
>     18  DejaVuSansMono Nerd Font             19 DroidSansMono Nerd Font              20 EnvyCodeR Nerd Font
>     21  FantasqueSansMono Nerd Font          22 FiraCode Nerd Font                   23 FiraMono Nerd Font
>     24  GeistMono Nerd Font                  25 GoMono Nerd Font                     26 Gohu Nerd Font
>     27  Hack Nerd Font                       28 Hasklug Nerd Font                    29 HeavyDataMono Nerd Font
>     30  Hurmit Nerd Font                     31 iM-Writing Nerd Font                 32 Inconsolata Nerd Font
>     33  InconsolataGo Nerd Font              34 InconsolataLGC Nerd Font             35 IntoneMono Nerd Font
>     36  Iosevka Nerd Font                    37 IosevkaTerm Nerd Font                38 IosevkaTermSlab Nerd Font
>     39  JetBrainsMono Nerd Font              40 Lekton Nerd Font                     41 Literation Nerd Font
>     42  Lilex Nerd Font                      43 MartianMono Nerd Font                44 Meslo Nerd Font
>     45  Monaspice Nerd Font                  46 Monofur Nerd Font                    47 Monoid Nerd Font
>     48  Mononoki Nerd Font                   49 M+ Nerd Font                         50 Noto Nerd Font
>     51  OpenDyslexic Nerd Font               52 Overpass Nerd Font                   53 ProFont Nerd Font
>     54  ProggyClean Nerd Font                55 RecMono Nerd Font                    56 RobotoMono Nerd Font
>     57  SauceCodePro Nerd Font               58 ShureTechMono Nerd Font              59 SpaceMono Nerd Font
>     60  Terminess Nerd Font                  61 Tinos Nerd Font                      62 Ubuntu Nerd Font
>     63  UbuntuMono Nerd Font                 64 VictorMono Nerd Font                 65 ZedMono Nerd Font
> 
> ---------------------------------------------
> Enter the numbers of the fonts to install (e.g., "1 2 3"):
> 10 11
> Downloading and installing BlexMono Nerd Font
> tar: This does not look like a tar archive
> xz: (stdin): File format not recognized
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> Downloading and installing CaskaydiaCove Nerd Font
> tar: This does not look like a tar archive
> xz: (stdin): File format not recognized
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> Font directories:
>         /home/jan/.local/share/fonts
>         /usr/local/share/fonts
>         /usr/share/fonts
>         /home/jan/.fonts
> /home/jan/.local/share/fonts: skipping, existing cache is valid: 0 fonts, 0 dirs
> /usr/local/share/fonts: skipping, no such directory
> /usr/share/fonts: skipping, no such directory
> /home/jan/.fonts: skipping, no such directory
> /var/cache/fontconfig: not cleaning non-existent cache directory
> /home/jan/.cache/fontconfig: cleaning cache directory
> /home/jan/.fontconfig: not cleaning non-existent cache directory
> ```
> 
> I removed the instruction `rm` instruction in line 164 to have a look at the files. Also I chose #11 and #12 now. Both fonts are 9 bytes long.
> 
> ```
> ❯ ll tmp
> total 16K
> drwxr-xr-x 2 jan 4.0K Sep 25 11:03 .
> drwx------ 9 jan 4.0K Sep 25 11:03 ..
> -rw-r--r-- 1 jan    9 Sep 25 11:03 CaskaydiaCove.tar.xz
> -rw-r--r-- 1 jan    9 Sep 25 11:03 CaskaydiaMono.tar.xz
> ❯ cat tmp/CaskaydiaCove.tar.xz
> Not Found%      
> ```

I think the error in download part happened because of [release page](https://github.com/ryanoasis/nerd-fonts/releases) names are radically different to that of the table in the main page of [repo](https://github.com/ryanoasis/nerd-fonts). Which wasn't an issue as I downloaded the font I use which is `Meslo`. The next part of selection happened because of my new adding of `more` functionality which I am going to fix.

**Comment by fam007e** [comment]
**Comment:**

The issues reported regarding font selection in the `nerdfonts_installer.sh` script have been resolved. The script now correctly increments the user-selected font numbers to match the displayed positions. Users can select fonts by their respective numbers without encountering errors related to invalid selections.

You can download the updated script in the latest release [v2024.09.25.1](https://github.com/fam007e/nerd_fonts_installer/releases/tag/v2024.09.25.1).

Thank you for your patience, and please feel free to test the updated script!

**Comment by fam007e** [comment]
> The issues reported regarding font selection in the `nerdfonts_installer.sh` script have been resolved. The script now correctly increments the user-selected font numbers to match the displayed positions. Users can select fonts by their respective numbers without encountering errors related to invalid selections.
> 
> You can download the updated script in the latest release [v2024.09.25.1](https://github.com/fam007e/nerd_fonts_installer/releases/tag/v2024.09.25.1).
> 
> Thank you for your patience, and please feel free to test the updated script!

Sorry keyboard issue hid this... 😅
